### PR TITLE
add option to bypass the check that the base ring is suitable

### PR DESCRIPTION
**Pull request by mezzarobba**
This makes it possible to do at least basic arithmetic with operators with
symbolic or inexact coefficients.

### CODE REVIEW

**Comment by mezzarobba** [comment]
More generally, how much of ore_algebra really depends on this assumption?
I wonder if it would be conceivable to remove the upfront test entirely and only
check the base ring in functions that really need it.

**Comment by mkauers** [comment]
I agree that the restriction on the base ring is too strict. What is really needed in some places is that we can recognize zero. For example, the leading coefficient should be nonzero in the mathematical sense. Probably there is a rather small number of fundamental functions such that all other functions requiring zero-testing of coefficients call one of these. Then we could move the tests there. The functions for getting the order or the leading coefficient of an operator may be among them.

**Comment by mezzarobba** [comment]
On Friday, 16 February 2024 08:28:44 CET mkauers wrote:
> What is really needed in some places is that we can recognize zero.

Thanks for the explanations. I suspect the linear algebra solvers also 
assumes a “suitable” ring and would need to be adapted?

-- 
Marc

**Comment by mkauers** [comment]
The solvers already include specialized checks, because they dispatch to different methods depending on the coefficient domain, and should throw an error if they are confronted with a domain they are not prepared for.

**Pull request merged**
