### PR TITLE
first large wave of autopep8 cleaning

### PR DESCRIPTION
**Pull request by fchapoton**
here we go, done purely with
`
pycodestyle -q --select=W391,W293,W291,E713,E712,E703,E702,E701,E502,E401,E306,E305,E303,E302,E301,E271,E266,E265,E262,E261,E251,E241,E211,E203,E202,E201 src/ | xargs autopep8 --select=W391,W293,W291,E713,E712,E703,E702,E701,E502,E401,E306,E305,E303,E302,E301,E271,E266,E265,E262,E261,E251,E241,E211,E203,E202,E201 -i`

### CODE REVIEW

**Comment by mezzarobba** [comment]
I couldn't comment before Manuel merged your changes, but in the future, I would prefer if you could avoid doing automated cleanup in analytic/.

**Comment by mkauers** [comment]
Shall I undo the merge?

**Comment by mezzarobba** [comment]
It depends. If you don't mind rewriting history (using `git reset --hard`) on a published branch, yes, please (or I can do it). If what you have in mind is to use `git revert`, then no: I can also review Frédéric's changes and only undo the ones I disagree with.

**Comment by fchapoton** [comment]
I have tried to choose only un-controversial changes, so maybe Marc will not have much to undo ?

**Comment by mezzarobba** [comment]
To explain myself: I see two different issues with automated cleanup. The first one is that, in my code at least, some of the deviations from the pep8 conventions are intentional and I prefer to keep them. The second one is that I use `git blame` all the time, and systematic cleanup can introduce a lot of noise.

**Comment by mezzarobba** [comment]
That being said, Manuel, you're the boss, do as you prefer :-).

**Comment by mezzarobba** [comment]
> I have tried to choose only un-controversial changes, so maybe Marc will not have much to undo ?

From a quick look at the diff, I disagree with almost all the changes to `analytic/` and `examples/`, but would probably not undo them all if they stay in the git history.

**Comment by mkauers** [comment]
OK, then let me suggest the following:
1) Marc, please bring us back to the version before the merge by a hard
reset
2) Frederic, afterwards, if you want, you are welcome to run the cleanup
again on all files except analytic/* and examples/*.
Thanks.

**Comment by fchapoton** [comment]
I agree, sorry for the trouble.

**Comment by mezzarobba** [comment]
Thanks Manuel. Done. Frédéric, no worries; I agree that the code in `ore_algebra` is not very clean (in many respects)...

**Pull request merged**
