### PR TITLE
First version of my code for the seminumeric factorization of differential operators

### PR DESCRIPTION
**Pull request by a-goyer**
I just cleaned my code for the factorization of differential operators thanks to the monodromy matrices.
Do not hesitate if you have any questions.

### CODE REVIEW

**Comment by mezzarobba** [comment]
@mkauers I had a look over the code with Alexandre. As far as I am concerned, it is ready to merge, but you may want to review at least the changes to `differential_operator_1_1` yourself. The git history is a bit of a mess, please tell us if you'd prefer a pull request with cleaner history. Also, we are not completely happy with the names of the methods `check_minimal_annihilator` and `check_irreducible` but couldn't think of anything better; any idea?

**Comment by mkauers** [comment]
Thanks for the pull request. I was going to suggest is_minimal_annihilator and is_irreducible as alternative names, but then I saw that that's how you had named them before you changed to check_*. What was the motivation for this change? To me, is_* seems more natural.

**Comment by a-goyer** [comment]
Thank you for the suggestion!

Let me answer for "irreducible" (it is the same for "minimal_annihilator"). We changed is_irreducible into check_irreducible for the following reason: you expect that is_irreducible returns whether the operator is irreducible or not. However, the method I propose can only certify that the operator is irreducible, and cannot say anything in the reducible case. My first proposition was is_irreducible with the following 2 possible outputs: either `True` if the method succeeds to certify that the operator is irreducible or `None` otherwise. Note that `None` can occur in the following cases: insufficient precision, reducible case (or non-Fuchsian case). For the sake of clarity, we replaced is_irreducible by check_irreducible and `None` by `False` but it is not completely satisfying.

I plan to add a method which computes the minimal annihilator in any case. For the same reason (no need to reconstruct a factor) that "check_irreducible" is faster than "right_factor" in the irreducible case, "check_minimal_annihilator" would be faster than this method in the minimal case.

**Comment by mkauers** [comment]
I see. So the problem is that the method checks only a sufficient condition. How would you like any of the following names?

is_definitely_irreducible
is_provably_irreducible
is_surely_irreducible
is_maybe_reducible
is_possibly_reducible
might_be_reducible
passes_numerical_irreducibility_condition

**Comment by a-goyer** [comment]
Thank you. I just changed into is_provably_irreducible and added some examples in order to make the signature clearer. However I am a bit afraid that the output `False` stays confusing for the client.

**Comment by mkauers** [comment]
OK, merged. Let's hope that the added adverb suggests users to have a look at the docstring. Thanks for sharing the code!

**Pull request merged**
